config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "users#index"
  resources :exercises
  resources :users do
    resources :trainingsplans do
      resources :collections
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :trainingsplan
  belongs_to :exercise
  
  
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  has_and_belongs_to_many :collections
  CATEGORIES = ["Chest", "Legs", "Back", "Arms", "Core"]

  validates :category, presence: true, inclusion: {in: CATEGORIES}
  validates :name, presence: true, uniqueness: true
end

app/models/trainingsplan.rb
class Trainingsplan < ApplicationRecord
  belongs_to :user
  has_many :exercises, through: :collection

  validates :goal, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trainingsplans
  has_many :collections, through: :trainingsplans
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  def create
    @trainingsplan = Trainingsplan.find(params[:trainingsplan_id])
    @collection = Collection.new(collection_params)
    @collection.trainingsplan = @trainingsplan
    if @collection.save
      redirect_to trainingsplan_path(@trainingsplan)
    else
      render "trainingsplan/show"
    end
  end

  def destroy
    @collection.destroy
    render "trainingsplan/show"
  end

  private

  def collection_params
    params.require(:collection).permit(:description, :exercise_id)
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:create, :update, :destroy, :show]
  
  def index
    @exercises = Exercise.all
  end
  
  def show  
  end

  def new
    @exercise = Exercise.new  
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.save
      redirect_to exercise_path(@exercise)
    else
      render :new
    end
  end

  def update
    @exercise.update(exercise_params)
    redirect_to exercise_path(@exercise)  
  end

  def destroy
    @cocktail.destroy
    redirect_to exercises_path  
  end

  def edit  
  end

  private

  def set_exercise
    @exercise = Exercise.find(params[:id])
  end

  def exercise_params
    params.require(:exercise).permit(:name, :category)
  end
end

app/controllers/trainingsplans_controller.rb
class TrainingsplansController < ApplicationController
  before_action :set_trainingsplan, only: [:show, :edit, :update, :destroy]
  def index
    @trainingsplans = Trainingsplan.all
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])  
  end

  def new
    @trainingsplan= Trainingsplan.new
    @user = User.find(params[:user_id])
    @trainingsplan.user = @user
  end

  def create
    @trainingsplan = Trainingsplan.new(trainingsplan_params)
    @user = User.find(params[:user_id])
    @trainingsplan.user = @user
    if @trainingsplan.save
      redirect_to user_trainingsplans_path(@user)
    else
      raise
    end
  end

  def edit
    @user = User.find(params[:user_id]) 
  end

  def destroy
    @trainingsplan.destroy
    redirect_to trainingsplans_path
  end

  def update
    @trainingsplan.update(trainingsplan_params)    
    redirect_to user_trainingsplan_path(@trainingsplan)
  end

  private

  def trainingsplan_params
    params.require(:trainingsplan).permit(:name, :goal)
  end

  def set_trainingsplan
    @trainingsplan = Trainingsplan.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
    @trainingsplan = Trainingsplan.where(user_id: params[:id])
 
  end

  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def edit
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/trainingsplans_helper.rb
module TrainingsplansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exercises/index.html.erb
<h1>All of our exercises <%= link_to "New Exercise", new_exercise_path, class: "btn btn-outline-primary" %></h1>
<div class="container">
  <div class="row justify-content-md-center" style="margin-bottom: 20px;">
    <% @exercises.each do |exercise| %>
    <div class="col-4 col-sm-4 col-md-4 col-lg-4 col-xl-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('')">
        <h1><%= link_to exercise.name, exercise, class: "card-title btn btn-outline-dark mx-auto" %></h1>     
      </div>
    </div> 
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSspExercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>  
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trainingsplans/_form.html.erb
<%= simple_form_for([@user, @trainingsplan]) do |f| %>
  <%= f.input :name %>
  <%= f.input :goal %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/trainingsplans/edit.html.erb
<%= render "form", user: @user, trainingsplan: @trainingsplan %>

app/views/trainingsplans/index.html.erb
<h2>List of Trainingsplans</h2> <%= link_to "Back to User", user_path(@user), class: "btn btn-primary"  %>
<ul style="list-style-type: none;">

<% @trainingsplans.each do |trainingsplan| %>
  <li>
    <%= trainingsplan.name %> for  
    <%= trainingsplan.goal %> 
    <%#  %><%= link_to "Edit Trainingsplan", edit_user_trainingsplan_path(trainingsplan[:id])  %>%>
  </li>
  <% end  %>
</ul>

<%= link_to "New Trainingsplan", new_user_trainingsplan_path, class: "btn btn-primary" %>

app/views/trainingsplans/new.html.erb
<%= render "form", user: @user, trainingsplan: @trainingsplan %>

app/views/trainingsplans/show.html.erb
<%= link_to "Back to Overview", user_trainingsplans_path, class: "btn btn-light" %>

<ul style="list-style-type: none;">

  <li>
    <%= @trainingsplan.name %> for  
    <%= @trainingsplan.goal %> 
    <%= link_to "Edit Trainingsplan", edit_user_trainingsplan_path  %>
  </li>
</ul>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>All of our Users <%= link_to "New user", new_user_path, class: "btn btn-outline-primary" %></h1>
<div class="container">
  <div class="row justify-content-md-center" style="margin-bottom: 20px;">
    <% @users.each do |user| %>
    <div class="col-4 col-sm-4 col-md-4 col-lg-4 col-xl-3">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('')">
        <h1><%= link_to user.name, user, class: "card-title btn btn-outline-dark mx-auto" %></h1>     
      </div>
    </div> 
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= link_to "Back to Overview", users_path, class: "btn btn-light" %>
<h2><%= @user.name %></h2>
<ul style="list-style-type: none;">

<% @user.trainingsplans.each do |trainingsplan| %>
  <li>
    <%= link_to trainingsplan.name, user_trainingsplan_path(@user) %> for  <%= trainingsplan.goal %>
    <%= link_to "Edit Trainingsplan", edit_user_trainingsplan_path(@user)   %>
  </li>
  <% end  %>
</ul>




  <%= link_to 'Edit User', edit_user_path(@user), class: "btn btn-secondary btn-outline-warning" %>
  <%= link_to 'Delete', user_path(@user), class: "btn btn-secondary btn-outline-danger",
      method: :delete,
      data: { confirm: "Are you sure"} %>
</div>